#!/usr/bin/env python3
"""Claude Code hook adapter for a DPM gate-mode demo.

The production substrate lives in runtime/dpm. This hook is deliberately thin:
it demonstrates the user-facing gate behavior by maintaining a small append-only
JSONL ledger and injecting/denying Claude tool calls when active correction
directives would make a pending action stale.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import os
import re
import shutil
import sys
from pathlib import Path
from typing import Any


CORRECTION_HINTS = (
    "actually",
    "correction",
    "correcting",
    "wrong",
    "instead",
    "replace",
    "forget",
    "do not use",
    "don't use",
    "ignore the prior",
    "invalid",
    "stale",
    "not ",
)

DECISION_TOOLS = {
    "Bash",
    "Edit",
    "Write",
    "MultiEdit",
    "NotebookEdit",
}

RISKY_BASH = re.compile(
    r"\b(git\s+(commit|push|merge|rebase|tag)|gh\s+pr|aws\s+|scp\s+|rsync\s+|"
    r"kubectl\s+|terraform\s+(apply|destroy)|rm\s+(-|/)|Remove-Item\b|"
    r"del\s+|move\s+|mv\s+|copy\s+|cp\s+|python\s+.*setup|bazel\s+(run|test|build))",
    re.IGNORECASE,
)


def utc_now() -> str:
    return _dt.datetime.now(_dt.UTC).isoformat(timespec="seconds")


def project_root() -> Path:
    env_root = (
        os.environ.get("CLAUDE_PROJECT_DIR")
        or os.environ.get("GEMINI_PROJECT_DIR")
        or os.environ.get("CURSOR_PROJECT_DIR")
        or os.environ.get("COPILOT_WORKSPACE_DIR")
    )
    if env_root:
        return Path(env_root).resolve()
    return Path.cwd().resolve()


def state_dir(root: Path) -> Path:
    return root / ".dpm-agent-hooks"


def state_path(root: Path) -> Path:
    return state_dir(root) / "state.json"


def ledger_path(root: Path) -> Path:
    return state_dir(root) / "ledger.jsonl"


def active_context_path(root: Path) -> Path:
    return state_dir(root) / "ACTIVE_CONTEXT.md"


def load_state(root: Path) -> dict[str, Any]:
    path = state_path(root)
    if not path.exists():
        return {"corrections": [], "last_events": []}
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def save_state(root: Path, state: dict[str, Any]) -> None:
    path = state_path(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    with tmp.open("w", encoding="utf-8", newline="\n") as f:
        json.dump(state, f, indent=2, sort_keys=True)
        f.write("\n")
    tmp.replace(path)
    write_active_context(root, state)


def append_ledger(root: Path, kind: str, event: dict[str, Any]) -> None:
    path = ledger_path(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    row = {
        "kind": kind,
        "created_at": utc_now(),
        "event": compact_event(event),
    }
    with path.open("a", encoding="utf-8", newline="\n") as f:
        f.write(json.dumps(row, sort_keys=True))
        f.write("\n")


def compact_event(event: dict[str, Any]) -> dict[str, Any]:
    compact = {
        "session_id": event.get("session_id"),
        "hook_event_name": event.get("hook_event_name"),
        "tool_name": event.get("tool_name"),
        "cwd": event.get("cwd"),
    }
    if "prompt" in event:
        compact["prompt"] = truncate(str(event.get("prompt", "")), 2000)
    if "tool_input" in event:
        compact["tool_input"] = scrub_large(event.get("tool_input"))
    if "tool_response" in event:
        compact["tool_response"] = scrub_large(event.get("tool_response"))
    if "trigger" in event:
        compact["trigger"] = event.get("trigger")
    return compact


def scrub_large(value: Any, limit: int = 4000) -> Any:
    if isinstance(value, str):
        return truncate(value, limit)
    if isinstance(value, list):
        return [scrub_large(item, limit) for item in value[:20]]
    if isinstance(value, dict):
        return {str(k): scrub_large(v, limit) for k, v in list(value.items())[:40]}
    return value


def truncate(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    return text[:limit] + "...<truncated>"


def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def write_active_context(root: Path, state: dict[str, Any]) -> None:
    path = active_context_path(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    corrections = active_corrections(state)
    lines = [
        "# DPM Verified Context",
        "",
        "This file is generated by `.claude/hooks/dpm_gate.py` for the Claude",
        "gate-mode demo. It is a correction-aware context patch, not source",
        "code and not a replacement for the Phase 3 C++ substrate.",
        "",
    ]
    if not corrections:
        lines += ["No active blocking corrections.", ""]
    else:
        lines += [
            "Active blocking corrections:",
            "",
        ]
        for corr in corrections:
            lines.append(f"- correction_id: `{corr['correction_id']}`")
            if corr.get("invalidated_facts"):
                lines.append(
                    "  - invalidated: "
                    + "; ".join(f"`{fact}`" for fact in corr["invalidated_facts"])
                )
            if corr.get("replacement_facts"):
                lines.append(
                    "  - replacement: "
                    + "; ".join(f"`{fact}`" for fact in corr["replacement_facts"])
                )
            lines.append(
                "  - rule: do not write, commit, deploy, or hand off memory that "
                "contains an invalidated fact."
            )
            lines.append("")
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))


def active_corrections(state: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        corr
        for corr in state.get("corrections", [])
        if corr.get("severity", "blocking") == "blocking"
    ]


def is_correction_prompt(prompt: str) -> bool:
    lowered = prompt.lower()
    return any(hint in lowered for hint in CORRECTION_HINTS)


def extract_correction(prompt: str) -> dict[str, Any]:
    invalidated: list[str] = []
    replacements: list[str] = []

    replace_match = re.search(
        r"\breplace\s+['\"]?(.{3,160}?)['\"]?\s+with\s+['\"]?(.{3,160}?)['\"]?(?:[.\n]|$)",
        prompt,
        flags=re.IGNORECASE,
    )
    if replace_match:
        invalidated.append(clean_fact(replace_match.group(1)))
        replacements.append(clean_fact(replace_match.group(2)))

    arrow_match = re.search(
        r"(.{3,160}?)\s*(?:->|=>)\s*(.{3,160}?)(?:[.\n]|$)", prompt
    )
    if arrow_match:
        invalidated.append(clean_fact(arrow_match.group(1)))
        replacements.append(clean_fact(arrow_match.group(2)))

    not_match = re.search(
        r"\bnot\s+['\"]?(.{3,160}?)['\"]?\s*(?:,|;|\.)\s*(?:use|it is|it's|instead)?\s*['\"]?(.{3,160}?)?['\"]?(?:[.\n]|$)",
        prompt,
        flags=re.IGNORECASE,
    )
    if not_match:
        invalidated.append(clean_fact(not_match.group(1)))
        if not_match.group(2):
            replacements.append(clean_fact(not_match.group(2)))

    forget_match = re.search(
        r"\b(?:forget|do not use|don't use|ignore)\s+['\"]?(.{3,160}?)['\"]?(?:[.\n]|$)",
        prompt,
        flags=re.IGNORECASE,
    )
    if forget_match:
        invalidated.append(clean_fact(forget_match.group(1)))

    invalidated = dedupe([fact for fact in invalidated if len(fact) >= 3])
    replacements = dedupe([fact for fact in replacements if len(fact) >= 3])

    return {
        "correction_id": f"claude-demo-{digest(prompt)}",
        "created_at": utc_now(),
        "severity": "blocking" if invalidated else "info",
        "reason_code": "user_prompt_correction",
        "correction_text": truncate(prompt, 1000),
        "invalidated_facts": invalidated,
        "replacement_facts": replacements,
    }


def clean_fact(text: str) -> str:
    text = re.sub(r"\s+", " ", text).strip(" \t\r\n'\"`:-")
    return truncate(text, 160)


def dedupe(items: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        key = item.lower()
        if key in seen:
            continue
        seen.add(key)
        out.append(item)
    return out


def merge_correction(state: dict[str, Any], correction: dict[str, Any]) -> bool:
    corrections = state.setdefault("corrections", [])
    for index, existing in enumerate(corrections):
        if existing.get("correction_id") == correction["correction_id"]:
            corrections[index] = correction
            return False
    corrections.append(correction)
    return True


def event_text(event: dict[str, Any]) -> str:
    parts: list[str] = []
    if "prompt" in event:
        parts.append(str(event.get("prompt", "")))
    tool_input = event.get("tool_input")
    if isinstance(tool_input, dict):
        for key in ("command", "file_path", "content", "new_string", "old_string"):
            if key in tool_input:
                parts.append(str(tool_input.get(key, "")))
        if "edits" in tool_input:
            parts.append(json.dumps(tool_input["edits"], sort_keys=True))
    elif tool_input is not None:
        parts.append(str(tool_input))
    return "\n".join(parts)


def is_decision_boundary(event: dict[str, Any]) -> bool:
    tool_name = str(event.get("tool_name", ""))
    normalized_tool = tool_name.lower()
    if tool_name in {"Edit", "Write", "MultiEdit", "NotebookEdit"} or normalized_tool in {
        "edit",
        "create",
        "write_file",
        "replace",
        "notebookedit",
    }:
        return True
    if tool_name.startswith("mcp__"):
        return bool(re.search(r"(write|create|update|delete|merge|deploy)", tool_name))
    if tool_name == "Bash" or normalized_tool in {"bash", "powershell", "run_shell_command"}:
        command = str(event.get("tool_input", {}).get("command", ""))
        return bool(RISKY_BASH.search(command))
    return tool_name in DECISION_TOOLS


def invalidated_hits(state: dict[str, Any], text: str) -> list[str]:
    hits: list[str] = []
    lowered = text.lower()
    for corr in active_corrections(state):
        for fact in corr.get("invalidated_facts", []):
            if fact and fact.lower() in lowered:
                hits.append(fact)
    return dedupe(hits)


def verified_context(state: dict[str, Any], root: Path) -> str:
    corrections = active_corrections(state)
    if not corrections:
        return (
            "DPM gate: no active blocking corrections in the demo ledger. "
            "Proceed normally."
        )
    lines = [
        "DPM gate: active correction-aware memory patch is in effect.",
        f"Read `{active_context_path(root)}` before acting on remembered context.",
        "Do not propagate invalidated facts into edits, commits, deploys, or handoffs.",
    ]
    for corr in corrections[-3:]:
        if corr.get("invalidated_facts"):
            lines.append(
                "Invalidated: "
                + "; ".join(f"`{fact}`" for fact in corr["invalidated_facts"])
            )
        if corr.get("replacement_facts"):
            lines.append(
                "Use instead: "
                + "; ".join(f"`{fact}`" for fact in corr["replacement_facts"])
            )
    return "\n".join(lines)


def normalize_event(event: dict[str, Any], agent: str) -> dict[str, Any]:
    """Convert the major CLI hook payload dialects into our internal shape."""
    out = dict(event)
    raw_name = (
        out.get("hook_event_name")
        or out.get("hookEventName")
        or out.get("event")
        or out.get("eventName")
        or ""
    )
    name = str(raw_name)
    aliases = {
        "sessionStart": "SessionStart",
        "SessionStart": "SessionStart",
        "startup": "SessionStart",
        "userPromptSubmitted": "UserPromptSubmit",
        "UserPromptSubmit": "UserPromptSubmit",
        "BeforeAgent": "UserPromptSubmit",
        "preToolUse": "PreToolUse",
        "PreToolUse": "PreToolUse",
        "BeforeTool": "PreToolUse",
        "beforeShellExecution": "PreToolUse",
        "permissionRequest": "PermissionRequest",
        "PermissionRequest": "PermissionRequest",
        "postToolUse": "PostToolUse",
        "PostToolUse": "PostToolUse",
        "AfterTool": "PostToolUse",
        "afterShellExecution": "PostToolUse",
        "afterFileEdit": "PostToolUse",
        "PostToolBatch": "PostToolBatch",
        "preCompact": "PreCompact",
        "PreCompact": "PreCompact",
        "stop": "Stop",
        "agentStop": "Stop",
        "Stop": "Stop",
        "sessionEnd": "SessionEnd",
        "SessionEnd": "SessionEnd",
    }
    out["hook_event_name"] = aliases.get(name, name)

    if "tool_name" not in out:
        out["tool_name"] = (
            out.get("toolName")
            or out.get("tool")
            or out.get("name")
            or infer_tool_name(out, agent)
            or ""
        )
    if "tool_input" not in out:
        args = out.get("toolArgs", out.get("args", out.get("toolInput", {})))
        if isinstance(args, str):
            try:
                args = json.loads(args)
            except json.JSONDecodeError:
                args = {"command": args}
        out["tool_input"] = args
    if "prompt" not in out:
        out["prompt"] = (
            out.get("userPrompt")
            or out.get("prompt")
            or out.get("message")
            or prompt_from_gemini_request(out)
            or ""
        )
    return out


def infer_tool_name(event: dict[str, Any], agent: str) -> str:
    if "command" in event:
        return "Bash"
    if agent == "cursor" and event.get("shell_command"):
        return "Bash"
    return ""


def prompt_from_gemini_request(event: dict[str, Any]) -> str:
    request = event.get("llm_request")
    if not isinstance(request, dict):
        return ""
    messages = request.get("messages")
    if not isinstance(messages, list):
        return ""
    for message in reversed(messages):
        if isinstance(message, dict) and message.get("role") == "user":
            return str(message.get("content", ""))
    return ""


def hook_response(
    agent: str, event_name: str, additional_context: str | None = None
) -> dict[str, Any]:
    if agent == "copilot":
        return {"additionalContext": additional_context} if additional_context else {}
    output: dict[str, Any] = {"hookSpecificOutput": {"hookEventName": event_name}}
    if additional_context:
        output["hookSpecificOutput"]["additionalContext"] = additional_context
    return output


def deny_pretool(agent: str, reason: str) -> dict[str, Any]:
    if agent == "gemini":
        return {"decision": "deny", "reason": reason, "systemMessage": reason}
    if agent == "copilot":
        return {"behavior": "deny", "message": reason, "interrupt": False}
    if agent == "cursor":
        return {"decision": "deny", "reason": reason}
    return {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": reason,
        }
    }


def allow_pretool(
    agent: str, reason: str, additional_context: str | None = None
) -> dict[str, Any]:
    if agent == "gemini":
        out: dict[str, Any] = {"decision": "allow", "systemMessage": reason}
        if additional_context:
            out["hookSpecificOutput"] = {
                "hookEventName": "BeforeTool",
                "additionalContext": additional_context,
            }
        return out
    if agent == "copilot":
        return {"additionalContext": additional_context} if additional_context else {}
    if agent == "cursor":
        return {"decision": "allow", "additionalContext": additional_context}
    out: dict[str, Any] = {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "allow",
            "permissionDecisionReason": reason,
        }
    }
    if additional_context:
        out["hookSpecificOutput"]["additionalContext"] = additional_context
    return out


def handle_hook(
    event: dict[str, Any], root: Path, agent: str
) -> dict[str, Any] | None:
    event = normalize_event(event, agent)
    state = load_state(root)
    event_name = str(event.get("hook_event_name", ""))
    append_ledger(root, event_name or "unknown", event)

    if event_name == "SessionStart":
        return hook_response(agent, "SessionStart", verified_context(state, root))

    if event_name == "UserPromptSubmit":
        prompt = str(event.get("prompt", ""))
        if is_correction_prompt(prompt):
            correction = extract_correction(prompt)
            added = merge_correction(state, correction)
            save_state(root, state)
            status = "registered" if added else "refreshed"
            return hook_response(
                agent,
                "UserPromptSubmit",
                f"DPM gate {status} a blocking correction directive.\n"
                + verified_context(state, root),
            )
        return hook_response(agent, "UserPromptSubmit", verified_context(state, root))

    if event_name in {"PreToolUse", "PermissionRequest"}:
        text = event_text(event)
        hits = invalidated_hits(state, text)
        if hits:
            return deny_pretool(
                agent,
                "DPM gate blocked this tool call because its input still contains "
                f"invalidated fact(s): {', '.join(hits)}. Re-read "
                f"{active_context_path(root)} and retry with the corrected memory."
            )
        if active_corrections(state) and is_decision_boundary(event):
            return allow_pretool(
                agent,
                "DPM gate allowed the action after checking active corrections.",
                verified_context(state, root),
            )
        return None

    if event_name in {"PostToolUse", "PostToolBatch"}:
        context = verified_context(state, root)
        return hook_response(
            agent, event_name, context if active_corrections(state) else None
        )

    if event_name == "PreCompact":
        state.setdefault("last_events", []).append(
            {
                "kind": "precompact_checkpoint",
                "created_at": utc_now(),
                "trigger": event.get("trigger"),
                "custom_instructions": event.get("custom_instructions", ""),
            }
        )
        state["last_events"] = state["last_events"][-20:]
        save_state(root, state)
        return {
            "decision": "block" if False else None,
            "hookSpecificOutput": {
                "hookEventName": "PreCompact",
                "additionalContext": "DPM demo ledger checkpointed before compaction.",
            },
        }

    if event_name in {"Stop", "SessionEnd"}:
        return hook_response(
            agent,
            event_name,
            "DPM gate ledger is current; no active blocking corrections."
            if not active_corrections(state)
            else verified_context(state, root),
        )

    return None


def read_event_stdin() -> dict[str, Any]:
    raw = sys.stdin.read()
    if not raw.strip():
        return {}
    return json.loads(raw)


def print_json(obj: dict[str, Any] | None) -> None:
    if not obj:
        return
    clean = {k: v for k, v in obj.items() if v is not None}
    print(json.dumps(clean, separators=(",", ":")))


def reset(root: Path) -> None:
    path = state_dir(root)
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)
    save_state(root, {"corrections": [], "last_events": []})


def seed(root: Path) -> None:
    state = load_state(root)
    correction = {
        "correction_id": "claude-demo-seed-transport-main-result",
        "created_at": utc_now(),
        "severity": "blocking",
        "reason_code": "demo_seed",
        "correction_text": (
            "Correction: transport as the main result is stale; credential "
            "theft is the main result."
        ),
        "invalidated_facts": ["transport as the main result"],
        "replacement_facts": ["credential theft is the main result"],
    }
    merge_correction(state, correction)
    save_state(root, state)
    append_ledger(root, "demo_seed", {"hook_event_name": "demo_seed", **correction})


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--agent",
        choices=["claude", "codex", "gemini", "cursor", "copilot"],
        default="claude",
    )
    parser.add_argument("--reset", action="store_true")
    parser.add_argument("--demo-seed", action="store_true")
    parser.add_argument("--status", action="store_true")
    args = parser.parse_args()

    root = project_root()
    if args.reset:
        reset(root)
    if args.demo_seed:
        seed(root)
    if args.status:
        state = load_state(root)
        print(active_context_path(root).read_text(encoding="utf-8"))
        print(f"ledger: {ledger_path(root)}")
        print(f"active_corrections: {len(active_corrections(state))}")
        return 0
    if args.reset or args.demo_seed:
        return 0

    try:
        event = read_event_stdin()
        response = handle_hook(event, root, args.agent)
        print_json(response)
        return 0
    except Exception as exc:  # Keep hook failures visible but non-catastrophic.
        print(f"DPM gate hook failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
